FROM node:18
LABEL authors="kwon"

WORKDIR /opt/server

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

ENV NODE_ENV=dev

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "start:dev"]
